enterprise/jetbroker/order/war/src/main/java/se/plushogskolan/jetbroker/order/bean/FlightRequestBean.java
package se.plushogskolan.jetbroker.order.bean;

import se.plushogskolan.jee.utils.map.HaversineDistance;
import se.plushogskolan.jetbroker.order.domain.airport.Airport;
import se.plushogskolan.jetbroker.order.domain.flightrequest.FlightRequest;
import se.plushogskolan.jetbroker.order.domain.plane.Plane;
import se.plushogskolan.jetbroker.order.domain.planetype.PlaneType;
import se.plushogskolan.jetbroker.order.util.EditFlightRequestUtil;

public class FlightRequestBean {

	private FlightRequest flightRequest;
	private Airport departureAirport;
	private Airport arrivalAirport;
	private String fuelPrice;
	private String travelDistance;
	private long planeId;
	private Plane offeredPlane;
	private PlaneType planeType;

	public FlightRequestBean() {

	}

	public FlightRequestBean(FlightRequest flightRequest,
			Airport departureAirport, Airport arrivalAirport) {

		setFlightRequest(flightRequest);
		setDepartureAirport(departureAirport);
		setArrivalAirport(arrivalAirport);
	}

	public String getOfferNicePrice() {
		double result = Double.valueOf(flightRequest.getOffer()
				.getOfferedPrice());
		return EditFlightRequestUtil.formatNumber(result);
	}

	public String getDistance() {
		double lat1 = departureAirport.getLatitude();
		double lng1 = departureAirport.getLongitude();
		double lat2 = arrivalAirport.getLatitude();
		double lng2 = arrivalAirport.getLongitude();

		return String.format("%.2f",
				HaversineDistance.getDistance(lat1, lng1, lat2, lng2));
	}

	public FlightRequest getFlightRequest() {
		return flightRequest;
	}

	public void setFlightRequest(FlightRequest flightRequest) {
		this.flightRequest = flightRequest;
	}

	public Airport getDepartureAirport() {
		return departureAirport;
	}

	public void setDepartureAirport(Airport departureAirport) {
		this.departureAirport = departureAirport;
	}

	public Airport getArrivalAirport() {
		return arrivalAirport;
	}

	public void setArrivalAirport(Airport arrivalAirport) {
		this.arrivalAirport = arrivalAirport;
	}

	public String getFuelPrice() {
		return fuelPrice;
	}

	public void setFuelPrice(String fuelPrice) {
		this.fuelPrice = fuelPrice;
	}

	public String getTravelDistance() {
		return travelDistance;
	}

	public void setTravelDistance(String travelDistance) {
		this.travelDistance = travelDistance;
	}

	public long getPlaneId() {
		return planeId;
	}

	public void setPlaneId(long planeId) {
		this.planeId = planeId;
	}

	public Plane getOfferedPlane() {
		return offeredPlane;
	}

	public void setOfferedPlane(Plane offeredPlane) {
		this.offeredPlane = offeredPlane;
	}

	public PlaneType getPlaneType() {
		return planeType;
	}

	public void setPlaneType(PlaneType planeType) {
		this.planeType = planeType;
	}

}

enterprise/jetbroker/order/war/src/main/java/se/plushogskolan/jetbroker/order/bean/PlaneBean.java
package se.plushogskolan.jetbroker.order.bean;

import se.plushogskolan.jetbroker.order.domain.planetype.PlaneType;

public class PlaneBean {

	private String id;
	private PlaneType planeType;
	private String planeTypeCode;
	private String description;
	private String code;
	private String fuelCost;
	private String travelTime;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PlaneType getPlaneType() {
		return planeType;
	}

	public void setPlaneType(PlaneType planeType) {
		this.planeType = planeType;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getPlaneTypeCode() {
		return planeTypeCode;
	}

	public void setPlaneTypeCode(String planeTypeCode) {
		this.planeTypeCode = planeTypeCode;
	}

	public String getFuelCost() {
		return fuelCost;
	}

	public void setFuelCost(String fuelCost) {
		this.fuelCost = fuelCost;
	}

	public String getTravelTime() {
		return travelTime;
	}

	public void setTravelTime(String travelTime) {
		this.travelTime = travelTime;
	}

}

enterprise/jetbroker/order/war/src/main/java/se/plushogskolan/jetbroker/order/mvc/MockFlightrequestController.java
package se.plushogskolan.jetbroker.order.mvc;

import javax.inject.Inject;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import se.plushogskolan.jetbroker.order.integration.simulator.MdbSimulator;

@Controller
@RequestMapping("/mock.html")
public class MockFlightrequestController {

	@Inject
	private MdbSimulator mdbSimulator;

	@RequestMapping(method = RequestMethod.GET)
	public ModelAndView getMockFlightrequest() {

		return new ModelAndView("mockFlightrequest");
	}

	@RequestMapping(method = RequestMethod.POST)
	public ModelAndView postMockFlightrequest() {

		mdbSimulator.createMockRequest();

		return new ModelAndView("redirect:index.html");
	}
}

enterprise/jetbroker/order/war/src/main/java/se/plushogskolan/jetbroker/order/mvc/PlaneController.java
package se.plushogskolan.jetbroker.order.mvc;

import javax.inject.Inject;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import se.plushogskolan.jetbroker.order.bean.PlaneBean;
import se.plushogskolan.jetbroker.order.domain.plane.Plane;
import se.plushogskolan.jetbroker.order.service.PlaneService;

@Controller
@RequestMapping("/plane.html")
public class PlaneController {

	@Inject
	private PlaneService planeService;

	@RequestMapping(method = RequestMethod.GET)
	public ModelAndView getPlane(PlaneBean bean) {
		ModelAndView modelAndView = new ModelAndView("plane");
		modelAndView.addObject("planeTypes", planeService.getPlaneTypes());
		modelAndView.addObject("plane", bean);

		return modelAndView;
	}

	@RequestMapping(method = RequestMethod.GET, params = { "id" })
	public ModelAndView editPlane(@RequestParam long id, PlaneBean bean) {
		Plane plane = planeService.getPlane(id);

		bean.setDescription(plane.getDescription());
		bean.setId(String.valueOf(plane.getId()));
		bean.setPlaneType(planeService.getPlaneTypeByCode(plane
				.getPlaneTypeCode()));

		ModelAndView result = new ModelAndView("plane");
		result.addObject("plane", bean);
		result.addObject("planeTypes", planeService.getPlaneTypes());

		return result;
	}

	@RequestMapping(method = RequestMethod.POST)
	public String postPlane(PlaneBean bean) {

		Plane plane = new Plane(bean.getDescription(), bean.getPlaneTypeCode());

		if (bean.getId().equals("")) {
			planeService.createPlane(plane);

		} else {
			plane.setId(Long.valueOf(bean.getId()));
			planeService.updatePlane(plane);
		}

		return "redirect:index.html";
	}
}

enterprise/jetbroker/order/war/src/main/webapp/WEB-INF/jsp/flightrequest.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link href="<%=request.getContextPath()%>/style/common.css"
	type="text/css" rel="stylesheet" />
<title>Edit flightrequest</title>
</head>
<body>
	<jsp:include page="header.jsp"></jsp:include>
	<h1>Edit flight request</h1>
	<div class="width-large">
		<div>
			<span class="bolder">ID</span> <span class="floatRight alignRight">${flightRequestBean.flightRequest.id}</span>
		</div>
		<div class="clear">
			<span class="bolder">Departure Airport</span> <span
				class="floatRight alignRight">${flightRequestBean.departureAirport.code},
				${flightRequestBean.departureAirport.name}</span>
		</div>
		<div class="clear">
			<span class="bolder">Arrival Airport</span> <span class="floatRight alignRight">${flightRequestBean.arrivalAirport.code},
				${flightRequestBean.arrivalAirport.name }</span>
		</div>
		<div class="clear">
			<span class="bolder">Date</span> <span class="floatRight alignRight">${flightRequestBean.flightRequest.niceDate}</span>
		</div>
		<div class="clear">
			<span class="bolder">No of passangers</span> <span class="floatRight alignRight">${flightRequestBean.flightRequest.numPassangers}</span>
		</div>
		<div class="clear">
			<span class="bolder">Distance (km)</span> <span class="floatRight alignRight">${flightRequestBean.distance}</span>
		</div>
		<br>
		<div class="clear">
			<span class="bolder">Fuel cost (liter)</span> <span class="floatRight alignRight">${flightRequestBean.fuelPrice}</span>
		</div>
	</div>
	<h1 class="clear">Our offer to customer</h1>
	<form:form action="/editFlightRequest.html?id=${flightRequestBean.flightRequest.id}" method="POST" commandName="offer">
	<form:errors class="errors" path="planeId"></form:errors>
		<table class="dataTable">
			<thead>
				<th></th>
				<th>Plane</th>
				<th>No of passangers</th>
				<th>Max speed (km/h)</th>
				<th>Fuel consumption (l/km)</th>
				<th>Total fuelcost</th>
				<th>Travel time (min)</th>
			</thead>
			<c:forEach items="${planes}" var="plane">
				<tr>
					<td><form:radiobutton path="planeId" value="${plane.id}" /></td>
					<td>${plane.planeType.name} ${plane.planeType.code}</td>
					<td>${plane.planeType.maxNoOfPassengers}</td>
					<td>${plane.planeType.maxSpeedKmH}</td>
					<td>${plane.planeType.fuelConsumptionPerKm}</td>
					<td>${plane.fuelCost} SEK</td>
					<td>${plane.travelTime}</td>
				</tr>
			</c:forEach>
		</table>
		<form:errors class="errors" path="offeredPrice"></form:errors>
		<div>
			<form:label path="offeredPrice">
			Offered price (SEK):
			<form:input path="offeredPrice" type="text" value="0.0" />
			</form:label>
		</div>
		<div>
			<form:input path="" type="submit" value="Submit offer" />
			<a href="<%=request.getContextPath()%>/editFlightRequest.html?rejected=1&id=${flightRequestBean.flightRequest.id}">Reject offer </a> <a
				href="<%=request.getContextPath()%>/index.html"> Cancel</a>
		</div>
	</form:form>
</body>
</html>

enterprise/jetbroker/order/war/src/main/webapp/WEB-INF/jsp/header.jsp
<div class="header">

<h1><a href="<%= request.getContextPath() %>/index.html">Jetbroker - ORDER</a></h1>

</div>

enterprise/jetbroker/order/war/src/main/webapp/WEB-INF/jsp/index.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>

<html>
<head>
<head>
<link href="<%=request.getContextPath()%>/style/common.css"
	type="text/css" rel="stylesheet" />

</head>
<body>
	<jsp:include page="header.jsp" />
	<!-- Request table -->
	<div>
		<h3>
			<img src="<%=request.getContextPath()%>/images/flightrequest.png" />Flight
			requests
		</h3>
		<a href="<%=request.getContextPath()%>/mock.html">Mock</a>
		<hr>
		<table class="dataTable">
			<thead>
				<th>ID</th>
				<th>Status</th>
				<th>Departure airport</th>
				<th>Arrival airport</th>
				<th>Date</th>
				<th>No passangers</th>
				<th>Offered price</th>
				<th>Offered plane</th>
				<th>Edit</th>
			</thead>
			<c:forEach items="${requests }" var="request">
				<tr>
					<td>${request.flightRequest.id}</td>
					<td>${request.flightRequest.statusNiceName}</td>
					<td>${request.departureAirport.name}
						(${request.departureAirport.code})</td>
					<td>${request.arrivalAirport.name}
						(${request.arrivalAirport.code})</td>
					<td>${request.flightRequest.niceDate}</td>
					<td>${request.flightRequest.numPassangers}</td>

					<c:choose>
						<c:when test="${request.flightRequest.offer.offeredPrice == null}">
							<td>0 SEK</td>
						</c:when>
						<c:otherwise>
							<td>${request.offerNicePrice} SEK</td>
						</c:otherwise>
					</c:choose>

					<c:choose>
						<c:when test="${request.planeType != null}">
							<td>${request.planeType.name} ${request.planeType.code}
								(${request.planeType.maxNoOfPassengers} seats)</td>
						</c:when>
						<c:otherwise>
							<td></td>
						</c:otherwise>
					</c:choose>
					<td><a
						href="<%=request.getContextPath()%>/editFlightRequest.html?id=${request.flightRequest.id}"><img
							src="<%=request.getContextPath()%>/images/edit.png"></a></td>
				</tr>
			</c:forEach>
		</table>
	</div>
	<!-- end Request table -->
	<!-- Our planes table -->
	<div>
		<h3>
			<img src="<%=request.getContextPath()%>/images/plane.png" />Our
			planes
		</h3>
		<hr>
		<div class="margin-small">
			<a class="button" href="<%=request.getContextPath()%>/plane.html">Create
				new plane</a>
		</div>
		<table class="dataTable">
			<thead>
				<th>ID</th>
				<th>Code</th>
				<th>Name</th>
				<th>Max passangers</th>
				<th>Range (km)</th>
				<th>Max speed (km/h)</th>
				<th>Description</th>
				<th>Edit</th>
			</thead>
			<c:forEach items="${planes }" var="plane">
				<tr>
					<td>${plane.id}</td>
					<td>${plane.code}</td>
					<td>${plane.planeType.name} ${plane.planeType.code}</td>
					<td>${plane.planeType.maxNoOfPassengers}</td>
					<td>${plane.planeType.maxRangeKm}</td>
					<td>${plane.planeType.maxSpeedKmH}</td>
					<td>${plane.description}</td>
					<td><a
						href="<%=request.getContextPath()%>/plane.html?id=${plane.id}"><img
							src="<%=request.getContextPath()%>/images/edit.png"></a></td>
				</tr>
			</c:forEach>
		</table>
	</div>
	<!-- end our planes table -->
	<!-- fuel div-->
	<div>
		<h2>
			<img src="<%=request.getContextPath()%>/images/gas.png" />Fuel price
		</h2>
		<hr>
		<p>Current cost is ${fuelprice} SEK</p>
	</div>
	<!-- end fuel div-->
</body>

</html>

enterprise/jetbroker/order/war/src/main/webapp/WEB-INF/jsp/mockFlightrequest.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>MockFlightrequest</title>
</head>
<body>
	<form action="<%= request.getContextPath() %>/mock.html" method="POST">
		<input type="submit"  value="Send mock flightrequest"/>
	</form>
</body>
</html>

enterprise/jetbroker/order/war/src/main/webapp/WEB-INF/jsp/plane.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet"
	href="<%=request.getContextPath()%>/style/common.css">
<title>Plane</title>
</head>
<body>
	<jsp:include page="header.jsp"></jsp:include>
	<div>
		<h2>
			<img src="<%=request.getContextPath()%>/images/plane.png">Edit
			plane
		</h2>
		<hr>
	</div>
	<div id="formDiv">
		<form:form commandName="plane" method="POST" action="/plane.html">
			<div>
				<label>ID</label> 
				<span>${plane.id}</span>
			</div>
			<div class="clear">
				<form:input path="id" type="hidden" value="${plane.id}" />
				<form:label path="planeType">Plane type</form:label>
				<form:select path="planeTypeCode">
					<form:option value=""></form:option>
					<form:options items="${planeTypes }" itemLabel="niceName"
						itemValue="code" />
				</form:select>
			</div>
			<div class="clear">
				<form:label path="description">Description</form:label>
				<form:textarea path="description" value="${plane.description }" />
			</div>
			<div class="clear">
				<input type="submit" value="Submit" /> <a
					href="<%=request.getContextPath()%>/index.html">Cancel</a>
			</div>
		</form:form>
	</div>
</body>
</html>